# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-06 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EXECUTOR_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField(db_column='Time', default='')),
                ('name', models.CharField(db_column='name', default='', max_length=20)),
                ('location', models.CharField(db_column='Location', max_length=200)),
                ('ip', models.CharField(db_column='IP', max_length=200)),
            ],
            options={
                'db_table': 'EXECUTOR',
            },
        ),
        migrations.CreateModel(
            name='MTD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('location', models.CharField(db_column='Location', max_length=200)),
                ('ip', models.CharField(db_column='IP', max_length=200)),
                ('time', models.BigIntegerField(db_column='Time')),
            ],
            options={
                'db_table': 'MTD',
            },
        ),
        migrations.CreateModel(
            name='NITAI',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=20, primary_key=True, serialize=False)),
                ('ip', models.CharField(db_column='IP', max_length=200)),
            ],
            options={
                'db_table': 'NITAI',
            },
        ),
        migrations.CreateModel(
            name='VM_INFO',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(db_column='Location', max_length=200)),
                ('ip', models.CharField(db_column='IP', max_length=200)),
            ],
            options={
                'db_table': 'VM_INFO',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mtd',
            unique_together=set([('name', 'time')]),
        ),
        migrations.AddField(
            model_name='executor_info',
            name='proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.NITAI'),
        ),
        migrations.AlterUniqueTogether(
            name='executor_info',
            unique_together=set([('name', 'time')]),
        ),
    ]
